### ISSUE TITLE
PB-GATT入网过程的疑惑

### ISSUE THREAD

**Issue by Nuclear6** [xiaolongba/HX_DK_FOR_NORDIC_52840_BLE_MESH_PUBLIC#3]
GATT入网的时候，为什么用的是Mesh Proxy Service，Mesh Provisioning Service怎么一点没说呢？

**Comment by xiaolongba** [comment]
那个我放在《Proxy Node的工作流程-》那里再详细解说，本篇主要的是入网过程。但是，文中描述的有所错误，配置入网用的是Mesh Provisioning Service而 Mesh Proxy Service是入网之后的交互才是用的这个服务。

**Comment by xiaolongba** [comment]
@BaiduSu

**Comment by Nuclear6** [comment]
代理配网过程中，ecdh的公私钥对怎么生成的呢？

**Comment by xiaolongba** [comment]
> 代理配网过程中，ecdh的公私钥对怎么生成的呢？

如果使用的是OOB的方式的话，那么就由OOB提供公钥给provisioner.如果没有用OOB的话，公私钥都由各自分别随便产生

不管是否用OOB，私钥都是由local自身产生。唯一不同的是公钥的交互。相关的内容我在《SIG MESH第一个实例---Generic On Off Model》中有更多的解释

**Comment by xiaolongba** [comment]
相关的错误描述已经修复，该ticket我就关闭了。有新的疑问可以再次新建一个ticket

**Comment by Nuclear6** [comment]
公私钥随机产生后，需要交换，交换后怎么计算ECDHSecret呢？

**Comment by xiaolongba** [comment]
> 公私钥随机产生后，需要交换，交换后怎么计算ECDHSecret呢？

计算公式如下“
> ECDHSecret = P-256(private key, peer public key)

更多相关的详情就参阅 **《Mesh Specification》** 的5.4.2.3 Exchanging public keys
